@hostname=localhost
@port=8000
POST http://{{hostname}}:{{port}}/products
Content-Type: application/json

{
  "name": "Product 2",
  "price": 100
}

###
GET http://{{hostname}}:{{port}}/products/92b1ee23-2e58-426a-b91c-afa961e2d9e1
Content-Type: application/json

###
PUT http://{{hostname}}:{{port}}/products/92b1ee23-2e58-426a-b91c-afa961e2d9e1
Content-Type: application/json

{
  "name": "Product 1 (updated 2)",
  "price": 100.5
}

###
DELETE http://{{hostname}}:{{port}}/products/92b1ee23-2e58-426a-b91c-afa961e2d9e1
