@hostname=localhost
@port=8000
@baseUrl=users
POST http://{{hostname}}:{{port}}/{{baseUrl}}
Content-Type: application/json

{
  "name": "John Doe",
  "email": "user1@email.com",
  "password": "123456"
}

###
GET http://{{hostname}}:{{port}}/{{baseUrl}}/92b1ee23-2e58-426a-b91c-afa961e2d9e1
Content-Type: application/json

###
POST http://{{hostname}}:{{port}}/{{baseUrl}}/generate_token
Content-Type: application/json

{
  "email": "user1@email.com",
  "password": "123456"
}

###
DELETE http://{{hostname}}:{{port}}/{{baseUrl}}/92b1ee23-2e58-426a-b91c-afa961e2d9e1
