basePath: /
host: localhost:8000
info:
  contact:
    email: brenoproti@gmail
    name: Breno Proti
  description: This is a sample server Product server.
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Go API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
